- name: Set hostname
  ansible.builtin.command: hostnamectl hostname {{ hostname.user_input }}
  changed_when: true

- name: Set RTC clock to UTC
  ansible.builtin.command: timedatectl set-local-rtc 0 --adjust-system-clock
  changed_when: true
