- name: Add aliases and exports
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: '{{ item }}'
  loop:
    - '[[ -f ~/.exports ]] && source ~/.exports'
    - '[[ -f ~/.aliases ]] && source ~/.aliases'
