- name: Check fzf version
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      REGEX="^.*([0-9]+\.[0-9]+\.[0-9]+).*$"
      [[ "$(fzf --version)" =~ $REGEX ]] && echo "${BASH_REMATCH[1]}"
  changed_when: false
  ignore_errors: true
  register: fzf_version

- name: Download fzf
  github-release-download:
    project: junegunn/fzf
    tag: 'v{{ versions.fzf }}'
    match_asset: '^.*linux_amd64.tar.gz$'
    dest: /tmp
  when: fzf_version.failed or fzf_version.stdout != versions.fzf
  register: fzf_download

- name: Unarchive fzf
  ansible.builtin.unarchive:
    src: '{{ fzf_download.dest }}'
    dest: /tmp
  when: not fzf_download is skipped

- name: Install fzf
  become: true
  ansible.builtin.copy:
    src: /tmp/fzf
    dest: /usr/local/bin/fzf
    owner: root
    group: root
    mode: '0755'
  when: not fzf_download is skipped
