- name: Ensure fonts directory exists
  become: true
  file:
    path: /usr/local/share/fonts
    state: directory
    owner: root
    mode: 0755

- name: Check if fonts already exist
  find:
    paths: /usr/local/share/fonts
    patterns: '{{ item[:9] }}*.ttf'
  loop: '{{ fonts }}'
  register: found_fonts

- name: Download fonts
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ versions.nerdfonts }}/{{ item[0] }}.zip
    dest: /tmp/
    mode: 0644
  when: item[1] == 0
  loop: '{{ fonts | zip(found_fonts.results | map(attribute="matched")) }}'
  register: downloaded_fonts

- name: Install fonts
  become: true
  unarchive:
    src: '{{ item.dest }}'
    dest: /usr/local/share/fonts/
    include: ['*.ttf']
  when: not item is skipped
  loop: '{{ downloaded_fonts.results }}'
