- name: Ensure fonts directory exists
  become: true
  file:
    path: /usr/local/share/fonts
    state: directory
    owner: root
    mode: 0755

- name: Check if fonts already exist
  find:
    paths: /usr/local/share/fonts
    patterns: '{{ item[:9] }}*.ttf'
  loop: '{{ settings.fonts }}'
  register: found_fonts

- name: Download fonts
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ versions.nerdfonts }}/{{ item }}.zip
    dest: /tmp/
    mode: 0644
  loop: '{{ found_fonts.results | selectattr("matched", "equalto", 0) | map(attribute="item") }}'
  register: downloaded_fonts

- name: Install fonts
  become: true
  unarchive:
    src: '{{ item.dest }}'
    dest: /usr/local/share/fonts/
    include: ['*.ttf']
  loop: '{{ downloaded_fonts.results }}'
  loop_control:
    label: '{{ item.item }}'
