- name: Set zsh as default shell
  become: true
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- import_tasks: install_fonts.yml

- name: Install zsh plugins
  git:
    repo: '{{ item.git }}'
    version: '{{ item.version | default("master") }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}'
    single_branch: true
  loop: '{{ zsh_plugins | selectattr("git", "defined") }}'

- name: Install zsh plugins
  get_url:
    url: '{{ item.url }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}.zsh'
    mode: 0700
  loop: '{{ zsh_plugins | selectattr("url", "defined") }}'

- name: Install starship
  become: true
  shell: set -o pipefail && curl -sS https://starship.rs/install.sh | sh
  changed_when: true
