- name: Set zsh as default shell
  become: yes
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- import_tasks: install_fonts.yml

- name: Install zsh plugins
  git:
    repo: '{{ item.git }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}'
  loop: '{{ zsh_plugins|selectattr("git", "defined") }}'

- name: Install zsh plugins
  get_url:
    url: '{{ item.url }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}.zsh'
  loop: '{{ zsh_plugins|selectattr("url", "defined") }}'

- name: Install starship
  become: yes
  shell: wget -O- https://starship.rs/install.sh | sh -s -- -y
