- name: Install and setup zsh
  ansible.builtin.import_tasks: zsh.yml

- name: Install starship prompt
  ansible.builtin.import_tasks: starship.yml

- name: Setup bash
  ansible.builtin.import_tasks: bash.yml
