- name: Set zsh as default shell
  become: yes
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- name: Install nerd fonts
  become: yes
  shell: |
    wget 'https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/{{ item }}.zip'
    DIR=$(mktemp -d)
    unzip {{ item }}.zip -d $DIR
    mkdir -p /usr/local/share/fonts && cp $DIR/*.ttf /usr/local/share/fonts/
    rm -rf $DIR && rm {{ item }}.zip
    fc-cache
  args:
    chdir: /tmp
  loop: [Hack, Meslo]

- name: Install zsh plugins
  git:
    repo: '{{ item.git }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}'
  loop: '{{ zsh_plugins|selectattr("git", "defined") }}'

- name: Install zsh plugins
  get_url:
    url: '{{ item.url }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}.zsh'
  loop: '{{ zsh_plugins|selectattr("url", "defined") }}'

- name: Install starship
  become: yes
  shell: wget -O- https://starship.rs/install.sh | sh -s -- -y
