- name: Download starship
  github-release-download:
    project: starship/starship
    tag: '{{ versions.starship }}'
    match_asset: '^.*x86_64-unknown-linux-gnu.tar.gz$'
    dest: /tmp
  when: not "starship " + versions.starship in check_versions.stdout
  register: starship_download

- name: Unarchive starship
  ansible.builtin.unarchive:
    src: '{{ starship_download.dest }}'
    dest: /tmp
  when: not starship_download is skipped

- name: Install starship
  become: true
  ansible.builtin.copy:
    src: /tmp/starship
    dest: /usr/local/bin/starship
    owner: root
    group: root
    mode: 0755
  when: not starship_download is skipped

- name: Write version to file
  ansible.builtin.lineinfile:
    path: ~/.ansible_versions
    line: starship {{ versions.starship }}
    regexp: ^starship
    create: true
    mode: 0644
  when: not starship_download is skipped
