- name: Check if starship should be installed/updated
  stat:
    path: /usr/local/bin/starship
    checksum_algorithm: sha256
  register: starship_file

- name: Download starship
  get_url:
    url: https://github.com/starship/starship/releases/download/v{{ versions.starship.version }}/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp
    mode: 0644
  when: >
    (not starship_file.stat.exists) or
    (starship_file.stat.checksum != versions.starship.checksum)
  register: starship_download

- name: Unarchive starship
  unarchive:
    src: '{{ starship_download.dest }}'
    dest: /tmp
  when: not starship_download is skipped

- name: Install starship
  become: true
  copy:
    src: /tmp/starship
    dest: /usr/local/bin/starship
    owner: root
    group: root
    mode: 0755
  when: not starship_download is skipped
