- name: Download starship
  get_url:
    url: https://github.com/starship/starship/releases/download/v{{ versions.starship }}/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp
    mode: 0644
  when: >
    (not "starship " + versions.starship in check_versions.stdout)
  register: starship_download

- name: Unarchive starship
  unarchive:
    src: '{{ starship_download.dest }}'
    dest: /tmp
  when: not starship_download is skipped

- name: Install starship
  become: true
  copy:
    src: /tmp/starship
    dest: /usr/local/bin/starship
    owner: root
    group: root
    mode: 0755
  when: not starship_download is skipped

- name: Write version to file
  lineinfile:
    path: ~/.ansible_versions
    line: starship {{ versions.starship }}
    regexp: ^starship
    create: true
    mode: 0644
  when: not starship_download is skipped
