- name: Set zsh as default shell
  become: true
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- name: Install zsh plugins (git)
  git:
    repo: '{{ item.git }}'
    version: '{{ item.version | default("master") }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}'
    single_branch: true
  loop: '{{ zsh_plugins | selectattr("git", "defined") }}'

- name: Install zsh plugins (url)
  get_url:
    url: '{{ item.url }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}.zsh'
    mode: 0700
  loop: '{{ zsh_plugins | selectattr("url", "defined") }}'

- name: Copy .zshrc
  template:
    src: .zshrc.j2
    dest: ~/.zshrc
    mode: 0600
