- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: '{{ username }}'
    shell: /bin/zsh

- name: Install zsh plugins (git)
  ansible.builtin.git:
    repo: '{{ item.git }}'
    version: '{{ item.version | default("master") }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.name }}'
    single_branch: true
  loop: '{{ settings.zsh_plugins | selectattr("git", "defined") }}'

- name: Install zsh plugins (url)
  ansible.builtin.get_url:
    url: '{{ item.url }}'
    dest: '{{ zsh_plugin_dir }}/{{ item.url | basename }}'
    mode: 0700
  loop: '{{ settings.zsh_plugins | selectattr("url", "defined") }}'

- name: Copy .zshrc
  ansible.builtin.template:
    src: .zshrc.j2
    dest: ~/.zshrc
    mode: 0600
