- name: Fedora desktop
  hosts: localhost
  vars_files:
    - vars.yml
    - versions.yml
  pre_tasks:
    - tags: always
      set_fact:
        settings: '{{ lookup("file", "vars/desktop.yml") | from_yaml }}'
  roles:
    - name: desktop
