- name: Ensure directories exist
  ansible.builtin.file:
    path: '~/{{ item.path }}'
    state: directory
    mode: '0700'
  loop: '{{ dotfiles_dirs }}'
  loop_control:
    label: '{{ item.path | basename }}'

- name: Copy dotfiles
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '~/{{ item.path }}'
    mode: '0600'
  loop: '{{ dotfiles_files | rejectattr("path", "match", ".*\.j2$") }}'
  loop_control:
    label: '{{ item.path | basename }}'

- name: Copy dotfiles templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '~/{{ item.path | regex_replace(".j2$", "") }}'
    mode: '0600'
  loop: '{{ dotfiles_files | selectattr("path", "match", ".*\.j2$") }}'
  loop_control:
    label: '{{ item.path | basename }}'
