- name: Set kernel parameters
  become: yes
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="{{ kernel_parameters|join(" ") }}"'
    regexp: '^GRUB_CMDLINE_LINUX="'
  notify: Run grub2-mkconfig

- name: Set sysctls
  become: yes
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
  loop: '{{ kernel_sysctls|dict2items }}'
