- name: Set kernel parameters
  become: true
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="{{ kernel_parameters | join(" ") }}"'
    regexp: '^GRUB_CMDLINE_LINUX="'
  notify: Run grub2-mkconfig

- name: Set sysctls
  become: true
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: true
  loop: '{{ kernel_sysctls | dict2items }}'
