- name: Add btrfs scrub systemd timer
  become: true
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  loop: [btrfs-scrub@.service, btrfs-scrub@.timer]

- name: Enable btrfs scrub systemd timer
  become: true
  ansible.builtin.systemd:
    name: btrfs-scrub@{{ "-" if item == "/" else item[1:] | replace("/", "-") }}.timer
    state: started
    enabled: true
    daemon_reload: true
  loop: '{{ btrfs_filesystems | map(attribute="mount") }}'
