- name: Install flatpak
  become: true
  dnf:
    name: flatpak
    state: present

- name: Enable flathub repository
  become: true
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- import_tasks: packages.yml
