- name: Install flatpak
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Enable flathub repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Install flatpak packages
  become: true
  community.general.flatpak:
    remote: flathub
    name: '{{ item }}'
    state: present
  loop: '{{ settings.flatpaks }}'
