- name: Install gnome extensions manager
  become: true
  dnf:
    name: gnome-extensions-app
    state: present

- name: Install extensions
  become: true
  dnf:
    name: '{{ gnome.extensions | selectattr("pkg", "defined") | map(attribute="pkg") }}'
    state: present

- name: Check enabled extensions
  command: gnome-extensions info {{ item }}
  loop: '{{ gnome.extensions | map(attribute="id") }}'
  register: enabled_extensions
  changed_when: false

- name: Enable extensions
  command: gnome-extensions enable {{ item.item }}
  when: 'not "State: ENABLED" in item.stdout'
  loop: '{{ enabled_extensions.results }}'
  loop_control:
    label: '{{ item.item }}'
