- name: Install gnome extensions manager
  become: true
  dnf:
    name: gnome-extensions-app
    state: present

- name: Install extensions (package)
  become: true
  dnf:
    name: '{{ settings.gnome.extensions | selectattr("pkg", "defined") | map(attribute="pkg") }}'
    state: present

- name: Install extensions (git)
  git:
    repo: '{{ item.git }}'
    version: '{{ item.version | default("master") }}'
    dest: ~/.local/share/gnome-shell/extensions/{{ item.id }}
    single_branch: true
  loop: '{{ settings.gnome.extensions | selectattr("git", "defined") }}'

- name: Check enabled extensions
  command: gnome-extensions list --disabled
  register: disabled_extensions
  changed_when: false

- name: Enable extensions
  command: gnome-extensions enable {{ item }}
  loop: >-
    {{ disabled_extensions.stdout_lines
       |intersect(settings.gnome.extensions | map(attribute="id")) }}
  changed_when: true
