- name: Install gnome extensions manager
  become: true
  dnf:
    name: gnome-extensions-app
    state: present

- name: Install extensions (package)
  become: true
  dnf:
    name: '{{ gnome.extensions | selectattr("pkg", "defined") | map(attribute="pkg") }}'
    state: present

- name: Install extensions (git)
  git:
    repo: '{{ item.git }}'
    version: '{{ item.version | default("master") }}'
    dest: ~/.local/share/gnome-shell/extensions/{{ item.id }}
    single_branch: true
  loop: '{{ gnome.extensions | selectattr("git", "defined") }}'

- name: Check enabled extensions
  command: gnome-extensions info {{ item }}
  ignore_errors: true
  loop: '{{ gnome.extensions | map(attribute="id") }}'
  register: enabled_extensions
  changed_when: false

- name: Enable extensions
  command: gnome-extensions enable {{ item.item }}
  when: 'not item.failed and not "State: ENABLED" in item.stdout'
  loop: '{{ enabled_extensions.results }}'
  loop_control:
    label: '{{ item.item }}'
