# must be done with shell because dnf plugin doesn't have swap
- name: Install full ffmpeg
  become: true
  ansible.builtin.shell: |
    ret=0
    if ! rpm -q ffmpeg; then
      dnf -y swap ffmpeg-free ffmpeg --allowerasing
      ret=1
    fi
    exit $ret
  when: (ansible_distribution_major_version | int) >= 37
  register: ffmpeg
  changed_when: ffmpeg.rc == 1
  failed_when: ffmpeg.rc not in [ 0, 1 ]

- name: Install media codecs
  become: true
  ansible.builtin.dnf:
    name:
      - '@Multimedia'
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - pipewire-codec-aptx
    state: present
    update_cache: true

- name: Install vaapi for hw video decoding
  become: true
  ansible.builtin.dnf:
    name:
      - ffmpeg
      - libva
      - libva-utils
    state: present
