- name: Install media codecs
  become: true
  dnf:
    name:
      - '@Multimedia'
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - pipewire-codec-aptx
    state: present
    update_cache: true

- name: Install vaapi for hw video decoding
  become: true
  dnf:
    name:
      - ffmpeg
      - libva
      - libva-utils
    state: present

# must be done with shell because dnf plugin doesn't have swap
- name: Install mesa-va-drivers-freeworld
  become: true
  shell: |
    ret=0
    if ! rpm -q mesa-va-drivers-freeworld; then
      dnf -y swap mesa-va-drivers mesa-va-drivers-freeworld
      ret=1
    fi

    if rpm -q mesa-va-drivers.i686; then
      dnf -y swap mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686
      ret=1
    fi

    exit $ret
  when: (ansible_distribution_major_version | int) >= 37
  register: va_drivers
  changed_when: va_drivers.rc == 1
  failed_when: va_drivers.rc not in [ 0, 1 ]
