# must be done with shell because dnf plugin doesn't have swap
- name: Install full ffmpeg
  become: true
  ansible.builtin.shell: |
    ret=0
    if ! rpm -q ffmpeg; then
      dnf -y swap ffmpeg-free ffmpeg --allowerasing
      ret=1
    fi
    exit $ret
  register: ffmpeg
  changed_when: ffmpeg.rc == 1
  failed_when: ffmpeg.rc not in [ 0, 1 ]

- name: Install media codecs
  become: true
  ansible.builtin.dnf:
    name:
      - '@Multimedia'
      - pipewire-codec-aptx
    state: present
    update_cache: true

- name: Install vaapi for hw video decoding
  become: true
  ansible.builtin.dnf:
    name:
      - libva
      - libva-utils
    state: present

- name: Install mesa vaapi drivers for hw video decoding
  become: true
  ansible.builtin.shell: |
    ret=0
    if ! rpm -q mesa-va-drivers-freeworld; then
      dnf -y swap mesa-va-drivers mesa-va-drivers-freeworld
      ret=1
    fi
    exit $ret
  register: mesa_drivers
  changed_when: mesa_drivers.rc == 1
  failed_when: mesa_drivers.rc not in [ 0, 1 ]
