- name: Enable RPM fusion repository
  become: true
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install packages
  become: true
  dnf:
    name: '{{ packages }}'
    state: present
    update_cache: true

- name: Install media codecs
  become: true
  dnf:
    name:
      - '@Multimedia'
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - pipewire-codec-aptx
    state: present
    update_cache: true

- name: Remove unneeded packages
  become: true
  dnf:
    name: '{{ remove_packages }}'
    state: absent
    autoremove: true
