- name: Enable RPM fusion repository
  become: true
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install packages
  become: true
  dnf:
    name: '{{ packages }}'

- name: Remove unneeded packages
  become: true
  dnf:
    name: '{{ remove_packages }}'
    state: absent
    autoremove: true
