- name: Ensure hostname is configured
  ansible.builtin.pause:
    prompt: 'Enter hostname'
  register: hostname
  when: ansible_hostname == "fedora" # default hostname
  changed_when: true
  notify: Set hostname

- name: Ensure RTC clock is in UTC
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      REGEX="RTC in local TZ: ([a-z]+)"
      [[ "$(timedatectl)" =~ $REGEX ]] && echo "${BASH_REMATCH[1]}"
  register: rtc
  changed_when: rtc.stdout == 'yes'
  notify: Set RTC clock to UTC

- name: Enable RPM fusion repository
  become: true
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: true

- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Install codecs
  ansible.builtin.import_tasks: codecs.yml
