- name: Get hostname
  pause:
    prompt: 'Enter hostname'
  register: hostname
  when: ansible_hostname == "fedora" # default hostname

- name: Set hostname
  hostname:
    name: '{{ hostname.user_input }}'
    use: systemd
  when: not hostname is skipped

- name: Enable RPM fusion repository
  become: true
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: true

- import_tasks: packages.yml
- import_tasks: codecs.yml
