- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: '{{ settings.packages }}'
    state: present
    update_cache: true

- name: Remove unneeded packages
  become: true
  ansible.builtin.dnf:
    name: '{{ settings.remove_packages }}'
    state: absent
    autoremove: true
