- name: Ensure pipewire group exists
  become: true
  ansible.builtin.group:
    name: pipewire
    state: present

- name: Add real time priority limits for pipewire group
  become: true
  ansible.builtin.copy:
    src: 95-pipewire.conf
    dest: /etc/security/limits.d/95-pipewire.conf
    mode: '0644'

- name: Add current user to pipewire group
  become: true
  ansible.builtin.user:
    name: '{{ lookup("env", "USER") }}'
    groups: pipewire
    append: true
