- name: Install syncthing
  become: true
  ansible.builtin.dnf:
    name: syncthing
    state: present

- name: Enable syncthing systemd service
  ansible.builtin.systemd:
    name: syncthing
    scope: user
    enabled: true
    state: started

- name: Install syncthingtray
  ansible.builtin.import_tasks: syncthing_tray.yml
