- name: Download syncthingtray
  github-release-download:
    project: Martchus/syncthingtray
    tag: '{{ versions.syncthingtray }}'
    match_asset: '^syncthingtray-.*-x86_64-pc-linux-gnu.tar.xz$'
    dest: /tmp
  when: not "syncthingtray " + versions.syncthingtray in check_versions.stdout
  register: syncthingtray_download

- name: Unarchive syncthingtray
  ansible.builtin.unarchive:
    src: '{{ syncthingtray_download.dest }}'
    dest: /tmp
    list_files: true
  when: not syncthingtray_download is skipped
  register: syncthingtray_unarchive

- name: Install syncthingtray
  become: true
  ansible.builtin.copy:
    src: /tmp/syncthingtray-x86_64-pc-linux-gnu
    dest: /usr/local/bin/syncthingtray
    owner: root
    group: root
    mode: 0755
  when: not syncthingtray_download is skipped

- name: Write version to file
  ansible.builtin.lineinfile:
    path: ~/.ansible_versions
    line: syncthingtray {{ versions.syncthingtray }}
    regexp: ^syncthingtray
    create: true
    mode: 0644
  when: not syncthingtray_download is skipped
