versions:
  starship: '1.11.0'
  nerdfonts: '2.2.2'
  syncthingtray: '1.3.0'

default_settings:
  packages:
    # essentials
    - curl
    - git
    - nano
    - micro
    - tmux
    - btop
    - lm_sensors

    # shell/cli utilities
    - zsh
    - bat
    - fd-find
    - ripgrep
    - git-delta
    - tldr

    # media
    - mpv
    - celluloid
    - foliate

    # browser
    - chromium-freeworld

    # misc
    - file-roller
    - meld

  remove_packages: []

  flatpaks:
    - com.jetbrains.IntelliJ-IDEA-Community
    - com.spotify.Client
    - com.bitwarden.desktop
    - md.obsidian.Obsidian
    - com.raggesilver.BlackBox
    - com.github.qarmin.czkawka
    - org.gtk.Gtk3theme.adw-gtk3
    - org.gtk.Gtk3theme.adw-gtk3-dark

  appimages: []

  # list of fonts to install from https://www.nerdfonts.com/
  fonts:
    - Hack
    - Meslo
    - JetBrainsMono

  zsh_plugin_dir: '~/.zsh/plugins'
  zsh_plugins:
    - { name: zsh-autosuggestions, git: https://github.com/zsh-users/zsh-autosuggestions }
    - { name: zsh-syntax-highlighting, git: https://github.com/zsh-users/zsh-syntax-highlighting }
    - { name: zsh-history-substring-search, git: https://github.com/zsh-users/zsh-history-substring-search }
    - { name: colored-man-pages, url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/colored-man-pages/colored-man-pages.plugin.zsh }
    - { name: extract, url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/extract/extract.plugin.zsh }
    - { name: safe-paste, url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/safe-paste/safe-paste.plugin.zsh }
    - { name: dirhistory, url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/dirhistory/dirhistory.plugin.zsh }
    - { name: sudo, url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh }
    - { name: fancy-ctrl-z, url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh }

  kernel:
    params:
      - quiet
      - splash
      - sysrq_always_enabled=1
      - nowatchdog

    sysctls:
      vm.swappiness: 1
      kernel.sysrq: 1

  gnome:
    # color theme from: https://github.com/Gogh-Co/Gogh
    # terminal_color_theme: vs-code-dark-plus

    gtk_theme: { name: adw-gtk3, url: https://github.com/lassekongo83/adw-gtk3/releases/download/v4.1/adw-gtk3v4-1.tar.xz }

    extensions:
      - { id: launch-new-instance@gnome-shell-extensions.gcampax.github.com, pkg: gnome-shell-extension-launch-new-instance }
      - { id: workspace-indicator@gnome-shell-extensions.gcampax.github.com, pkg: gnome-shell-extension-workspace-indicator }
      - { id: appindicatorsupport@rgcjonas.gmail.com, pkg: gnome-shell-extension-appindicator }
      - { id: dash-to-dock@micxgx.gmail.com, pkg: gnome-shell-extension-dash-to-dock }
      - { id: just-perfection-desktop@just-perfection, pkg: gnome-shell-extension-just-perfection }
      - { id: openweather-extension@jenslody.de, pkg: gnome-shell-extension-openweather }
      - { id: clipboard-indicator@tudmotu.com, git: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git }
      - { id: Vitals@CoreCoding.com, git: https://github.com/corecoding/Vitals.git }

    # xkb_options: []

# merged with settings
extra_settings: {}
