- name: Ensure fonts directory exists
  become: true
  ansible.builtin.file:
    path: /usr/local/share/fonts
    state: directory
    owner: root
    mode: '0755'

- name: Check nerd fonts version
  ansible.builtin.command: /bin/cat /usr/local/share/fonts/.ansible_version_nerdfonts
  changed_when: false
  ignore_errors: true
  register: nerdfonts_version

- name: Download nerd fonts
  github-release-download:
    project: ryanoasis/nerd-fonts
    tag: 'v{{ versions.nerdfonts }}'
    match_asset: '^{{ item }}.tar.xz$'
    dest: /tmp/{{ item }}.tar.xz
  when: nerdfonts_version.failed or nerdfonts_version.stdout != versions.nerdfonts
  loop: '{{ settings.fonts.nerd_fonts }}'
  register: nerdfonts_download

- name: Install nerd fonts
  become: true
  ansible.builtin.unarchive:
    src: /tmp/{{ item }}.tar.xz
    dest: /usr/local/share/fonts/
    include: ['*.ttf']
  when: not nerdfonts_download is skipped
  loop: '{{ settings.fonts.nerd_fonts }}'
  notify: Update fontconfig cache

- name: Write version to file
  become: true
  ansible.builtin.copy:
    content: '{{ versions.nerdfonts }}'
    dest: /usr/local/share/fonts/.ansible_version_nerdfonts
    mode: '0644'
  when: not nerdfonts_download is skipped

- name: Install font packages
  become: true
  ansible.builtin.dnf:
    name: '{{ settings.fonts.packages }}'
    state: present
  notify: Update fontconfig cache
